pantry_project/pantry/urls.py
from django.urls import path

from pantry import views

app_name = "pantry"

urlpatterns = [
    path("", views.index, name="index"),
    path("about/", views.about, name="about"),

    path("login/", views.login, name="login"),
    path("signup/", views.signup, name="signup"),
    path("logout/", views.logout, name="logout"),

    path("recipes/", views.recipes, name="recipes"),
    path("recipes/<int:user_id>/<int:recipe_id>", views.recipe, name="recipe"),

    path("create-a-recipe/", views.create_a_recipe, name="create-a-recipe"),

    path("<int:user_id>", views.user_profile, name="user-profile"),
    path("edit-profile/", views.edit_profile, name="edit-profile"),

    path("<int:user_id>/user-recipes/", views.user_recipes, name="user-recipes"),
    path("<int:user_id>/saved-recipes/", views.saved_recipes, name="saved-recipes"),
    path("<int:user_id>/user-reviews/", views.user_reviews, name="user-reviews"),

    path("like_review/", views.like_review, name="like-review"),
]

pantry_project/pantry_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from pantry import views

urlpatterns = [
    path("", views.index, name="index"),
    # any URL that starts with "pantry/" will be handled by the pantry app
    path("pantry/", include("pantry.urls")),
    path("admin/", admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pantry_project/pantry/models.py
from django.db import models
from django.contrib.auth.models import User
import os


class Cuisine(models.Model):

    type = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.type


class Category(models.Model):

    type = models.CharField(max_length=100, unique=True)

    class Meta:
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.type


class Recipe(models.Model):

    # helper
    def recipe_upload_path(self, filename):
        # get base filename
        filename = os.path.basename(filename)
        # return correct media folder using their user ID and recipe ID
        dir_name = "user-id-" + str(self.user.pk)
        recipe_id = "recipe-id-" + str(self.pk)
        return os.path.join(dir_name, "recipes", recipe_id, filename)

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    cuisine = models.ForeignKey(Cuisine, on_delete=models.CASCADE)
    categories = models.ManyToManyField(Category, blank=True)

    title = models.CharField(max_length=200)
    image = models.ImageField(upload_to=recipe_upload_path)
    desc = models.CharField(max_length=500)
    ingredients = models.CharField(max_length=2000)
    steps = models.CharField(max_length=10_000)
    prep = models.CharField(max_length=4)
    cook = models.CharField(max_length=4)
    difficulty = models.CharField(max_length=1)
    pub_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title


class UserProfile(models.Model):

    # helper
    def userprofile_upload_path(self, filename):
        # get base filename
        filename = os.path.basename(filename)
        # return correct media folder using their user ID and recipe ID
        dir_name = "user-id-" + str(self.user.pk)
        return os.path.join(dir_name, "profile", filename)

    user = models.OneToOneField(User, on_delete=models.CASCADE)

    image = models.ImageField(upload_to=userprofile_upload_path, blank=True)
    bio = models.CharField(max_length=200, blank=True)

    def __str__(self):
        return self.user.username


class Review(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE, related_name="reviews")

    review = models.CharField(max_length=500)
    likes = models.IntegerField(default=0)
    pub_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ("user", "recipe")


class SavedRecipes(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE, related_name="saves")

    pub_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ("user", "recipe")


class LikedReviews(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    review = models.ForeignKey(Review, on_delete=models.CASCADE)


class StarredRecipes(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE, related_name="ratings")

    value = models.IntegerField()

pantry_project/pantry/forms.py
from django import forms
from django.contrib.auth.models import User
from pantry.models import UserProfile, Recipe, Review, Cuisine


class UserForm(forms.ModelForm):
    username = forms.CharField(widget=forms.TextInput(attrs={"id": "username"}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={"id": "password"}))
    confirm_password = forms.CharField(
        widget=forms.PasswordInput(attrs={"id": "confirm-password"})
    )

    class Meta:
        model = User
        fields = ("username", "password")


class UserProfileForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        kwargs["label_suffix"] = ""
        super().__init__(*args, **kwargs)

    image = forms.ImageField(
        required=False, widget=forms.ClearableFileInput(attrs={"id": "image"})
    )
    bio = forms.CharField(required=False, widget=forms.Textarea(attrs={"id": "bio"}))

    class Meta:
        model = UserProfile
        fields = ("image", "bio")

pantry_project/pantry/views.py
from django.shortcuts import render
from django.contrib import auth
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect
from django.urls import reverse
from django.http import HttpResponse
from django.db.models import Q, Count, Avg
from pantry.models import *
from pantry.forms import *
from pantry.helpers import *

SPACER = "<SPACER>"

def index(request):

    # user is using search bar
    if request.method == "POST":
        search_query = request.POST.get("search_query")
        # send in url parameters with get request
        return redirect(reverse("pantry:recipes") + "?search_query=" + search_query)
    rated_recipes = Recipe.objects.annotate(rating=Avg("ratings__value"))
    highest_rated_recipes = rated_recipes.order_by("-rating", "-pub_date")[:10]
    newest_recipes = Recipe.objects.order_by("-pub_date")[:10]

    context_dict = {
        "highest_rated_recipes": highest_rated_recipes,
        "newest_recipes": newest_recipes,
        "num_highest_rated": len(highest_rated_recipes),
        "num_newest": len(newest_recipes),
    }

    return render(request, "pantry/index.html", context=context_dict)


def about(request):
    return render(request, "pantry/about.html")


def recipes(request):

    context_dict = {}

    # user is searching and not page refresh
    if request.GET.get("request", False):

        search_query = request.GET.get("search_query")

        # only display results if user has given a search query
        if not search_query:
            return render(request, "pantry/recipe-response.html")

        difficulties = request.GET.get("selected_difficulty").split(SPACER)
        cuisines = request.GET.get("selected_cuisines").split(SPACER)
        categories = request.GET.get("selected_categories").split(SPACER)
        sort = request.GET.get("selected_sort").split(SPACER)[0]

        # queries
        search_query_query = Q(title__startswith=search_query)

        difficulty_query = Q()
        for difficulty in difficulties:
            if difficulty:
                difficulty_query |= Q(difficulty=difficulty)

        cuisine_query = Q()
        for cuisine in cuisines:
            if cuisine:
                cuisine_query |= Q(cuisine=Cuisine.objects.get(type=cuisine))

        category_query = Q()
        for category in categories:
            if category:
                category_query |= Q(categories=Category.objects.get(type=category))

        # apply filters
        recipes = Recipe.objects.filter(
            search_query_query & difficulty_query & cuisine_query & category_query
        ).annotate(num_saves=Count("saves", distinct=True))

        recipes = recipes.annotate(rating=Avg("ratings__value"))
        
        # apply sort
        if sort == "rating":
            recipes = recipes.order_by("-rating")
        elif sort == "reviews":
            recipes = recipes.annotate(num_reviews=Count("reviews", distinct=True))
            recipes = recipes.order_by("-num_reviews")
        elif sort == "saves":
            recipes = recipes.order_by("-num_saves")
        else:
            recipes = recipes.order_by("-pub_date")

        context_dict["recipes"] = recipes

        return render(request, "pantry/recipe-response.html", context=context_dict)

    # user was redirected from index page
    elif request.GET.get("search_query", False):

        search_query = request.GET.get("search_query")

        # only display results if user has given a search query
        if not search_query:
            return render(request, "pantry/recipe-response.html")

        search_query_query = Q(title__startswith=search_query)
        recipes = Recipe.objects.filter(search_query_query).annotate(
            num_saves=Count("saves", distinct=True)
        )
        recipes = recipes.annotate(rating=Avg("ratings__value"))
        context_dict["recipes"] = recipes
        context_dict["search_query"] = search_query

    cuisines = Cuisine.objects.all().values_list("type", flat=True)
    categories = Category.objects.all().values_list("type", flat=True)

    context_dict["cuisines"] = cuisines
    context_dict["categories"] = categories

    return render(request, "pantry/recipes.html", context=context_dict)


def signup(request):

    # user is signing up
    if request.method == "POST":

        user_form = UserForm(request.POST)
        profile_form = UserProfileForm(request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user
            profile.bio = "Hey there, I'm a new user!"
            profile.save()

            auth.login(request, user)

            return redirect(reverse("pantry:index"))

        else:
            return render(
                request,
                "pantry/signup.html",
                {"user_form": user_form, "profile_form": profile_form},
            )

    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

    return render(
        request,
        "pantry/signup.html",
        {"user_form": user_form, "profile_form": profile_form},
    )


def login(request):

    context_dict = {"success": True}

    # user is logging in
    if request.method == "POST":

        username = request.POST.get("username")
        password = request.POST.get("password")

        user = auth.authenticate(username=username, password=password)

        if user:
            auth.login(request, user)
            return redirect(reverse("pantry:index"))
        else:
            context_dict["success"] = False
            return render(request, "pantry/login.html", context=context_dict)

    else:
        return render(request, "pantry/login.html", context=context_dict)


@login_required
def logout(request):
    auth.logout(request)
    return redirect(reverse("pantry:index"))


def recipe(request, user_id, recipe_id):

    context_dict = {}
    recipe = Recipe.objects.get(id=recipe_id)

    if request.method == "POST":

        # user is bookmarking
        if "data[bookmarked]" in request.POST:

            bookmarked = request.POST.get("data[bookmarked]")
            if bookmarked == "true":
                SavedRecipes.objects.get(user=request.user, recipe=recipe).delete()
                return return_ajax_success(
                    request.user, recipe, SavedRecipes, "success", "fail"
                )
            elif bookmarked == "false":
                SavedRecipes.objects.create(user=request.user, recipe=recipe).save()
                return return_ajax_success(
                    request.user, recipe, SavedRecipes, "fail", "success"
                )

        # user is rating
        elif "data[rating]" in request.POST:
            new_rating = request.POST.get("data[rating]")

            if int(new_rating) > 5:
                return HttpResponse("Invalid rating")


            prev_rating = StarredRecipes.objects.filter(
                user=request.user, recipe=recipe
            )
            # delete if previously rated
            if prev_rating.exists():
                prev_rating.delete()
            
            # add new rating
            StarredRecipes.objects.create(
                user=request.user, recipe=recipe, value=new_rating
            )
            return return_ajax_success(
                request.user, recipe, StarredRecipes, "fail", "success"
            )

        # user is posting a review
        elif request.POST.get("reason") == "review":

            request_review = request.POST.get("review")
            Review.objects.create(
                user=request.user, recipe=recipe, review=request_review
            ).save()

    # logged in user data
    if request.user.is_authenticated:
        # bookmark
        bookmark_exists = SavedRecipes.objects.filter(user=request.user, recipe=recipe)
        context_dict["bookmarked"] = True if bookmark_exists else False

        # liking reviews
        liked_reviews = LikedReviews.objects.filter(
            user=request.user, review__recipe=recipe
        )
        liked_review_ids = list(liked_reviews.values_list("review__id", flat=True))
        context_dict["liked_reviews"] = liked_review_ids

        # star rating
        try:
            user_rating = StarredRecipes.objects.get(user=request.user, recipe=recipe)
            context_dict["user_rating"] = user_rating.value
        except StarredRecipes.DoesNotExist:
            context_dict["user_rating"] = 0
        # make sure not to double count by excluding users rating
        context_dict["all_ratings"] = list(
            recipe.ratings.all()
            .exclude(user=request.user)
            .values_list("value", flat=True)
        )

    # general page data
    other_user = User.objects.get(id=user_id)
    has_reviewed = has_reviewed_helper(request.user, recipe)
    if not "all_ratings" in context_dict:
        context_dict["all_ratings"] = list(
            recipe.ratings.all().values_list("value", flat=True)
        )

    context_dict["recipe"] = recipe
    context_dict["reviews"] = Review.objects.filter(recipe=recipe)
    context_dict["ingredients"] = recipe.ingredients.split(SPACER)
    context_dict["steps"] = recipe.steps.split(SPACER)
    context_dict["my_profile"] = is_own_profile(request.user, other_user)
    context_dict["has_reviewed"] = has_reviewed
    context_dict["saves"] = SavedRecipes.objects.filter(recipe=recipe).count()

    return render(request, "pantry/recipe.html", context=context_dict)


@login_required
def create_a_recipe(request):

    # user is creating a recipe
    if request.method == "POST":

        # get our cuisine instance
        user_cuisine = Cuisine.objects.get(type=request.POST.get("cuisine"))
        # get our categories strings

pantry_project/templates/pantry/login.html
{% extends 'pantry/base/base.html' %} {% load staticfiles %}

<!-- CSS -->
{% block css_block %}
<link rel="stylesheet" href="{% static 'css/pages/login.css' %}" />
{% endblock %}

<!-- JS -->
{% block js_block %}
<script type="module" src="{% static 'js/pages/login.js' %}"></script>
{% endblock %}

<!-- TITLE -->
{% block title_block %} Login {% endblock %}

<!-- CONTENT -->
{% block main_block %}
<!-- HEADER -->
<h3>Login</h3>

<form
  role="form"
  id="login-form"
  method="post"
  action="{% url 'pantry:login' %}"
>

  {% csrf_token %}

  <!-- FIELDS -->
  <h4>Username</h4>
  <input type="text" id="username" name="username" value="" />
  <h4>Password</h4>
  <input type="password" id="password" name="password" value="" />
  <input id="submit" type="submit" value="Login" />

  <!-- ERROR MESSAGE -->
  {% if success %}
  <h5 id="error-message"></h5>
  {% else %}
  <h5 id="error-message" class="error-message-active">
    Invalid username or password
  </h5>
  {% endif %}

  <!-- SIGNUP LINK -->
  <h4>New to Pantry?</h4>
  <h4>Sign Up <a href="{% url 'pantry:signup' %}">HERE</a></h4>

</form>
{% endblock %}

pantry_project/templates/pantry/recipe-response.html
{% load staticfiles %}

{% load custom_filters %}

{% for recipe in recipes %}
      <a class="recipe" href="{% url 'pantry:recipe' recipe.user.id recipe.id %}">
        <img class="recipe-image" src="{{ MEDIA_URL }}{{ recipe.image }}" />
        <ul>
          <li>{{ recipe.title }}</li>
          <li>
            <img src="{% static 'images/star.svg' %}" />
            {% if recipe.rating %}
            {{ recipe.rating|round_num }} 
            {% else %}
            0.00
            {% endif %}
          </li>
          {% if recipe.num_saves == 1 %}
          <li>{{ recipe.num_saves }} save</li>
          {% else %}
          <li>{{ recipe.num_saves }} saves</li>
          {% endif %}
          <li id="recipe-difficulty">{{ recipe.difficulty }}</li>
          <li>{{ recipe.cuisine }}</li>
          <li>Prep - {{ recipe.prep }}h</li>
          <li>Cook - {{ recipe.cook }}h</li>
        </ul>
      </a>
{% endfor %}

pantry_project/templates/pantry/recipe.html
{% extends 'pantry/base/base.html' %} {% load staticfiles %}

<!-- CSS -->
{% block css_block %}
<link rel="stylesheet" href="{% static 'css/pages/recipe.css' %}" />
{% endblock %}

<!-- JS -->
{% block js_block %}
<script type="text/javascript">
  const csrfToken = "{{ csrf_token }}";
  const recipeId = {{ recipe.id }};
  const allRatings = JSON.parse("{{ all_ratings|safe }}");
  var userRating = parseInt("{{user_rating}}")
</script>

<script type="module" src="{% static 'js/pages/recipe.js' %}"></script>
{% endblock %}

<!-- TITLE -->
{% block title_block %} Recipe {% endblock %}

<!-- CONTENT -->
{% block main_block %}
<!-- RECIPE HEADER -->
<header class="recipe-header">
  <!-- USERNAME / PUBLISHED DATE -->
  <div class="left-aside">
    <a class="user" href="{% url 'pantry:user-profile' recipe.user.id %}">
      {{ recipe.user.username }}
    </a>
    <p>{{ recipe.pub_date }}</p>
  </div>

  <!-- RECIPE TITLE -->
  <h3>{{ recipe.title }}</h3>

  <!-- STARS / BOOKMARK -->
  <div class="right-aside">
    {% if not my_profile and user.is_authenticated %}

    <div id="stars"></div>

    <!-- BOOKMARK -->
    {% if bookmarked == True %}
    <button id="bookmark" name="bookmarked" value="true"></button>
    {% else %}
    <button id="bookmark" name="bookmarked" value="false"></button>
    {% endif %}
    

    {% endif %}
  </div>
</header>

<!-- RECIPE INFO -->
<div class="recipe-info">
  <!-- IMAGE / DESCRIPTION -->
  <div class="description">
    <img src="{{ MEDIA_URL }}{{ recipe.image }}" />
    <p>{{ recipe.desc }}</p>
  </div>

  <!-- SUB INFO -->
  <div class="info">
    <ul>
      <li>
        <img src="{% static 'images/star.svg' %}" />
        <div id="rating-text"></div>
      </li>
      {% if saves == 1 %}
      <li id="saves" data-save={{saves}}>{{ saves }} save</li>
      {% else %}
      <li id="saves" data-save={{saves}}>{{ saves }} saves</li>
      {% endif %}
      <li id="recipe-difficulty">{{ recipe.difficulty }}</li>
      <li>{{ recipe.cuisine }}</li>
      <li>Prep - {{ recipe.prep }}h</li>
      <li>Cook - {{ recipe.cook }}h</li>
    </ul>
  </div>
</div>

<!-- RECIPE FACTS -->
<div class="recipe-facts">
  <!-- STEPS -->
  <div class="steps">
    <h5>Steps</h5>
    <ul>
      {% for step in steps %}
      <li>{{ step }}</li>
      {% endfor %}
    </ul>
  </div>

  <!-- INGREDIENTS -->
  <div class="ingredients">
    <h5>Ingredients</h5>
    <ul>
      {% for ingredient in ingredients %}
      <li>{{ ingredient }}</li>
      {% endfor %}
    </ul>
  </div>

  <!-- CATEGORIES -->
  <div class="categories">
    <h5>Categories</h5>
    <ul>
      {% for category in recipe.categories.all %}
      <li>{{ category.type }}</li>
      {% endfor %}
    </ul>
  </div>
</div>

<!-- REVIEWS -->
<h3 id="review-header">Reviews</h3>

<!-- POST REVIEW -->
{% if user.is_authenticated and not my_profile and not has_reviewed %}
<form
  role="form"
  id="post-review-form"
  method="post"
  enctype="multipart/form-data"
  action="{% url 'pantry:recipe' recipe.user.id recipe.id %}"
>
  {% csrf_token %}
  <input type="hidden" name="reason" value="review" />
  <textarea
    id="review"
    placeholder="I love this recipe..."
    name="review"
  ></textarea>
  <div class="user-review-submit-container">
    <input type="submit" id="user-review-submit" value="post" />
  </div>
</form>
{% endif %}

<!-- REVIEW LIST -->
<div id="review-url" data-url="{% url 'pantry:like-review' %}"></div>
{% for review in reviews %}
<div class="review">
  <div class="review-aside">
    <!-- USERNAME / PUBLISHED DATE -->
    <div>
      <a class="user" href="{% url 'pantry:user-profile' review.user.id %}">
        {{ review.user.username }}
      </a>
      <p>{{ review.pub_date }}</p>
    </div>

    <!-- RATING -->
    <div class="review-rating">
      {% if user.is_authenticated %}
        {% if review.id in liked_reviews %}
          <button class="review-heart" value="{{ review.id }}" data-liked="true"></button>
        {% else %}
          <button class="review-heart" value="{{ review.id }}" data-liked="false"></button>
        {% endif %}
      {% else %}
      <img
        class="review-heart-image"
        src="{% static 'images/heart-empty.svg' %}"
      />
      {% endif %}
      <p class="review-likes">{{ review.likes }}</p>
    </div>
  </div>

  <!-- REVIEW TEXT -->
  <p class="review-text">{{ review.review }}</p>
</div>
{% endfor %} 

{% endblock %}

pantry_project/templates/pantry/recipes.html
{% extends 'pantry/base/base.html' %} {% load staticfiles %}
{% load custom_filters %}

<!-- CSS -->
{% block css_block %}
<link rel="stylesheet" href="{% static 'css/pages/recipes.css' %}" />
{% endblock %}

<!-- JS -->
{% block js_block %}
<script type="text/javascript">
  var searchQuery = "{{ search_query }}";
</script>
<script type="module" src="{% static 'js/pages/recipes.js' %}"></script>
{% endblock %}

<!-- TITLE -->
{% block title_block %} Recipes {% endblock %}

<!-- CONTENT -->
{% block main_block %}
<!-- HEADER -->
<h3>Find Recipes</h3>

<div id="search-form">
  <!-- LEFT COLUMN -->
  <div class="left-container">
    <!-- CREATE-A-RECIPE LINK -->
    {% if user.is_authenticated %}
    <a href="{% url 'pantry:create-a-recipe' %}">Create A Recipe</a>
    {% endif %}

    <h5>Filter</h5>

    <!-- FILTER DIFFICULTY -->
    <div class="container-difficulty">
      <button id="btn-beginner" class="btn-difficulty" value="beginner">
        beginner
      </button>
      <button id="btn-intermediate" class="btn-difficulty" value="intermediate">
        intermediate
      </button>
      <button id="btn-expert" class="btn-difficulty" value="expert">
        expert
      </button>
    </div>

    <!-- FILTER CUISINE -->
    <div id="cuisine-list">
      {% for cuisine in cuisines %}
      <button class="btn-cuisine" value="{{ cuisine }}">{{ cuisine }}</button>
      {% endfor %}
    </div>

    <!-- FILTER CATEGORY -->
    <div id="category-list">
      {% for category in categories %}
      <button class="btn-category" value="{{ category }}">
        {{ category }}
      </button>
      {% endfor %}
    </div>

    <h5>Sort By</h5>

    <!-- SORT BY -->
    <div class="container-sort-by">
      <button id="btn-rating" class="btn-sort-by" value="rating">rating</button>
      <button id="btn-newest" class="btn-sort-by" value="newest">newest</button>
      <button id="btn-saves" class="btn-sort-by" value="saves">saves</button>
      <button id="btn-reviews" class="btn-sort-by" value="reviews">reviews</button>
    </div>
  </div>

  <!-- RIGHT COLUMN -->
  <div class="right-container">
    <!-- SEARCH BAR -->
    <div class="search-bar">
      <input type="text" id="search" name="search_query" placeholder="search for a recipe" value="{{ search_query }}" />
    </div>

    <!-- SEARCH RESULTS -->
    <div id="search-results">
      {% for recipe in recipes %}
      <a class="recipe" href="{% url 'pantry:recipe' recipe.user.id recipe.id %}">
        <img class="recipe-image" src="{{ MEDIA_URL }}{{ recipe.image }}" />
        <ul>
          <li>{{ recipe.title }}</li>
          <li>
            <img src="{% static 'images/star.svg' %}" />
            {% if recipe.rating %}
            {{ recipe.rating|round_num }}
            {% else %}
            0.00
            {% endif %}
          </li>
          {% if recipe.num_saves == 1 %}
          <li>{{ recipe.num_saves }} save</li>
          {% else %}
          <li>{{ recipe.num_saves }} saves</li>
          {% endif %}
          <li id="recipe-difficulty">{{ recipe.difficulty }}</li>
          <li>{{ recipe.cuisine }}</li>
          <li>Prep - {{ recipe.prep }}h</li>
          <li>Cook - {{ recipe.cook }}h</li>
        </ul>
      </a>
      {% endfor %}
    </div>
  </div>
</div>
{% endblock %}

pantry_project/templates/pantry/user-profile.html
{% extends 'pantry/base/base.html' %} {% load staticfiles %}

<!-- CSS -->
{% block css_block %}
<link rel="stylesheet" href="{% static 'css/pages/user-profile.css' %}" />
{% endblock %}

<!-- JS -->
{% block js_block %}
<script type="module" src="{% static 'js/pages/user-profile.js' %}"></script>
{% endblock %}

<!-- TITLE -->
{% block title_block %} User Profile {% endblock %}

<!-- CONTENT -->
{% block main_block %}
<!-- HEADER -->
<h3 id="user">{{ profileuser.username }}</h3>

<div class="super-container">

  <!-- BIO -->
  <div class="bio">
    {% if profileuser_profile.image %}
    <img src="{{ MEDIA_URL }}{{ profileuser_profile.image }}" />
    {% else %}
    <img class="default-profile-img" src="{% static 'images/profile-default.jpg' %}" />
    {% endif %}
    <p>{{ profileuser_profile.bio }}</p>
  </div>

  <!-- TOOLS -->
  <div class="tools">

    <!-- SEARCH -->
    <div class="search">
      <input type="text" id="search" name="search_query" placeholder="search a user" />
      <ul id="search-results"></ul>
    </div>

    <!-- LINKS -->
    <ul class="links">
      {% if own_profile %}

      <!-- include 'edit-profile' and 'create-a-recipe' links -->
      <li>
        <a href="{% url 'pantry:edit-profile' %}">Edit Profile</a>
      </li>
      <li>
        <a href="{% url 'pantry:create-a-recipe' %}">Create A Recipe</a>
      </li>
      <li>
        <a href="{% url 'pantry:user-recipes' profileuser.id %}">My Recipes</a>
      </li>
      <li>
        <a href="{% url 'pantry:user-reviews' profileuser.id %}">My Reviews</a>
      </li>
      <li>
        <a href="{% url 'pantry:saved-recipes' profileuser.id %}">My Saved Recipes</a>
      </li>

      {% else %}

      <!-- include other users name in link text -->
      <li>
        <a href="{% url 'pantry:user-recipes' profileuser.id %}">{{ profileuser.username }}'s Recipes</a>
      </li>
      <li>
        <a href="{% url 'pantry:user-reviews' profileuser.id %}">{{ profileuser.username }}'s Reviews</a>
      </li>
      <li>
        <a href="{% url 'pantry:saved-recipes' profileuser.id %}">{{ profileuser.username }}'s Saved Recipes</a>
      </li>

      {% endif %}
    </ul>

  </div>

</div>
{% endblock %}

pantry_project/templates/pantry/user-response.html
{% load staticfiles %}

{% for user in users %}
<li><a href="{% url 'pantry:user-profile' user.id %}">{{user.username}}</a></li>
{% endfor %}